scalar JSON

interface Block {
  _type: String!
  ref: ID
}

type StaticText implements Block {
  id: ID!
  ref: ID
  _type: String!
  content: JSON
}


input StaticTextInput {
  id: ID!
  content: String!
  locale: String!
}

type Page {
  id: ID!
  slug: String
  published: Boolean
  layout: String
  parent: Page
  title: JSON
  linkText: JSON
  sections: JSON
}

input PageInput {
  id: ID
  slug: String
  published: Boolean
  layout: String
  parent: ID
  title: String
  linkText: String
}

input BlockInput {
  page: ID!
  section: String!
  _type: String!
}

input BlockRefInput {
  page: ID!
  ref: ID!
}

type Query {
  pages: [Page]
  page(id: ID!): Page
  staticText(id: ID!): StaticText
}

type Mutation {
  upsertPage(page: PageInput!, locale: String): Page
  addBlock(block: BlockInput!): ID
  removeBlock(block: BlockRefInput!): Boolean
  saveStaticText(input: StaticTextInput!): StaticText
  attachImage(type: String!, id: ID!, url: String!): Boolean
}