mutation upsertPage($page: PageInput!, $locale: String) {
    upsertPage(page: $page, locale: $locale) {
      id
      slug
      title
      linkText
      position
      parent {id}
      layout
      published
      sections
      properties
    }
  }